// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpl5P6RS-YrqMm1rgZFE3YrraUWXG2G0A',
    appId: '1:50500000763:web:fee5523f88424e2e47495e',
    messagingSenderId: '50500000763',
    projectId: 'uber-map-management',
    authDomain: 'uber-map-management.firebaseapp.com',
    databaseURL: 'https://uber-map-management-default-rtdb.firebaseio.com',
    storageBucket: 'uber-map-management.appspot.com',
    measurementId: 'G-BNY2NDQCE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKaScDpiZ613f1FuLRIdeZMVRl34ZwyHI',
    appId: '1:50500000763:android:de116ef65031008b47495e',
    messagingSenderId: '50500000763',
    projectId: 'uber-map-management',
    databaseURL: 'https://uber-map-management-default-rtdb.firebaseio.com',
    storageBucket: 'uber-map-management.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHND1GTn2X8eqaJLG5qnf9IhyD0B7klPY',
    appId: '1:50500000763:ios:894ddb9c32416b5247495e',
    messagingSenderId: '50500000763',
    projectId: 'uber-map-management',
    databaseURL: 'https://uber-map-management-default-rtdb.firebaseio.com',
    storageBucket: 'uber-map-management.appspot.com',
    iosClientId: '50500000763-dms6q0s96ob33f7e4dosped2vu76avke.apps.googleusercontent.com',
    iosBundleId: 'com.example.uberMapManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHND1GTn2X8eqaJLG5qnf9IhyD0B7klPY',
    appId: '1:50500000763:ios:894ddb9c32416b5247495e',
    messagingSenderId: '50500000763',
    projectId: 'uber-map-management',
    databaseURL: 'https://uber-map-management-default-rtdb.firebaseio.com',
    storageBucket: 'uber-map-management.appspot.com',
    iosClientId: '50500000763-dms6q0s96ob33f7e4dosped2vu76avke.apps.googleusercontent.com',
    iosBundleId: 'com.example.uberMapManagement',
  );
}
